import sort_objects_by_property from './sort_objects/sort_objects_by_property.js'
import sort_objects_by_property_and_position from './sort_objects/sort_objects_by_property_and_position.js'

export let sort_objects_by_property = sort_objects_by_property
export let sort_objects_by_property_and_position = sort_objects_by_property_and_position
